### ISSUE TITLE
Vector Addition -  master checklist

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#1]
# Vector Addition master checklist

## Design
- [x] **Sim folder and design doc created** (Date: 04/18/2019)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed** [suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821)
- [x] **Learning goals and standards identified** (Date: 04/25/2019)
- [x] **Design concept complete**  (Date: 04/25/2019)
- [x] **Wireframes complete** (Date: 05/06/2019)
- [x] **Mockups complete** (Date: 05/16/2019)
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion** (N/A - not planned for iO in near future)
- [ ] **Interviews complete** (Date: //)
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 10/23/2019)
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas (see #205)
  - [x] No new feature requests
- [x] **Pre-publication items**
  - [x] Auxilary screenshots (up to 3 additional) - #222
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder - #254 
  - [x] Sim primer draft - #256 
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive - #255 
  - [x] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use) - #255 
- [x] **Post-publication items**
  - [x] Share new features, design challenges, and treats with group!
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //)

## Implementation
- [x] **Repository created** (Date: 5/9/19)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 5/9/2019)
- [x] **Sim is "feature complete"** (Date: 8/14/2019)
- [x] **Code review completed** - N/A, we'll be doing an implementation post mortem
- [x] **Pre-publication items**
  - [x] Main screenshot - see #222
  - [x] Verify credits - see #98
- [x] **Published** (Date: 11/5/19)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [x] **Dev testing started** (Date: 10/3/2019)
- [x] **Dev testing completed** (Date: 10/7/2019)
- [x] **First RC published** (Date: 10/23/2019)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 11/5/19)

**Comment by pixelzoom** [comment]
I updated the "Implementation" portion of the checklist, based on GitHub history.

**Comment by pixelzoom** [comment]
All tasks in the _Implementation_ and _QA_ sections have been completed.

**Comment by pixelzoom** [comment]
Remaining items for @arouinfar to address are being tracked in #256 and #275.  So closing this issue.
