### ISSUE TITLE
TODO LIST (for near future)

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#14]
In order of priority

- [x] move the modelViewTransform to commonModel
- [x] make the origin drag snap to a minor line grid so there is no decimals 
- [x] clean up vector model and its api (@veillette is this done?)
- [x] transfer logic of VectorNode to Vector (@veillette is this done?)
- [x] add labels to the vector panel next to the vector icon (@brandonLi8  got this)
- [x] make vector not be added to the model until it is released on initial drop 
- [x] update the API for the view since the ModelViewTransform is now a Property.
- [x] transfer logic of VectorComponentsNode to Vector
- [ ] re add the bounds for vector drag
- [x] setup two scenes for explore 1d by creating a Graph.js model (similar to graphing lines) (@brandonLi8  can start this)
- [x] reinstate the three additional screens
- [x] clean up constants
- [x] add a color file
- [x] properties should use .value instead of .get()
- [x] create a sumNode to enable sum (looks like @veillette  is doing this)
- [x] Graph Control Panel strings must have a max Length and pass string test
- [x] in VectorPanelDisplay, select a vector text should be vertically aligned
- [x] vectors should be active only when dropped onto grid
- [x] create two icons for cartesian and polar snap to grid features (@brandonLi8 can do this in the future)
- [x] stylize the origin circle
- [x] you should be able to active a vector by clicking on the label. And you should be able to translate the vector by dragging the label (needed for 0 vectors)
- [x] add erase button, add remove listeners to the vector panel (@brandonLi8 )
- [x] ComponentStylesRadioButtons need to have a grid layout
- [x] add a scene model , @brandonLi8 , each scene can have multiple "vector sets" and each screen can have multiple scenes

**Comment by veillette** [comment]
More 
 - [ ] the gridPanel should be renamed graphPanel

**Comment by brandonLi8** [comment]
Closing, as all but one are complete and that one is added into the new todo list in #43
