### ISSUE TITLE
new TODO list

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#43]
Feel free to add to this
- [x] make each equation type be a separate scene.
- [x] finish coefficient selector panel (now that each equation is one scene #64 , this will be slightly different)
- [x] display coefficient on labels. 
- [x] do the equation type radio button
- [x ] do the equation graph control panel
- [ ] do the base vectors box
- [x] yellow label on active vectors
- [x] Hide Sum when no vectors in grid.
If a vector has zero magnitude:
Don’t show Angle in grid
Inspect: x & y components 0.0
Inspect: angle displays noValue, — 

Zero components
Hide 0.0 Value
Magnitude and component value on 
- [x] allow negative components on componetn labels
- [x] fix fonts of label node
- [ ] clip vector
- [x] vector groups 3 and 4, and they should have their own sum visible property
- [x] angles shouldn't show unless the vector is active
- [x] labels on vectors in lab screen shouldn't show unless its active
- [x] be able to take vectors out of the graph by dragging a certain distance once it hits the edge
- [x] animate the vector when its not dropped in the graph
- [x]  add drag bounds for vector tip
- [x]  add correct vector label positioning
- [x] fix #40 
- [x] add polar / cartesian mode
- [x] fix labels on component nodes
- [x] what should we do if the vector is dropped outside of the graph? (tracked on #50)
- [x] reproduce #33 and fix
- [x] make inspect vector panel text width fixed (c is slightly smaller than a, shifting the whole panel)
- [x] vector Creator panel is almost there, but slightly off: 
![image](https://user-images.githubusercontent.com/42391580/59982610-4aac7e00-95d2-11e9-93bd-a3eb9ed7d9aa.png)
![image](https://user-images.githubusercontent.com/42391580/59982612-51d38c00-95d2-11e9-8409-c65c061f038b.png)

The label of the vectors should be in the same spot, currently it is next to the vectors, so on vertical it shifts the labels.
- [x] explore 2D has inspect vector panel default to open, but explore 1d is default to closed
- [x] Ariel wants us to publish a dev version
- [ ] equation screen 😔
- [x] attributesVectorProperty needs to be renamed to something better :)
- [x] add reset on vectorSum

**Comment by brandonLi8** [comment]
- [ ] - labels should be made of not only formula node, but with a text node next to it to keep the font consistent. Example:
![image](https://user-images.githubusercontent.com/42391580/60473367-051f2f00-9c2a-11e9-961f-167918d9b4e6.png)
